-- SQLite
SELECT CASE
            WHEN SUBSTR(productname, 0, 5) LIKE '19%' 
                 OR SUBSTR(productname, 0, 5) LIKE '20%'
            THEN SUBSTR(productname, 0, 5)
            ELSE NULL
       END as year,
       CASE
            WHEN productName LIKE '%Harley%' THEN 'Harley-Davidson'
            WHEN productName LIKE '%Renault%' THEN 'Renault'
            WHEN productName LIKE '%Guzzi%' THEN 'Moto Guzzi'
            WHEN productName LIKE '%Alfa%' THEN 'Alfa Romeo'
            WHEN productName LIKE '%Lancia%' THEN 'Lancia'
            WHEN productName LIKE '%Ford%' THEN 'Ford'
            WHEN productName LIKE '%Ferrari%' THEN 'Ferrari'
            WHEN productName LIKE '%Setra%' THEN 'Setra'
            WHEN productName LIKE '%Corvair%' THEN 'Chevrolet'
            WHEN productName LIKE '%Dodge%' THEN 'Dodge'
            WHEN productName LIKE '%Plymouth%' THEN 'Chrysler'
            WHEN productName LIKE '%Chev%' THEN 'Chevrolet'
            WHEN productName LIKE '%Mazda%' THEN 'Mazda'
            WHEN productName LIKE '%Lincoln%' THEN 'Lincoln'
            WHEN productName LIKE '%Benz%' OR productName LIKE '%Mercedes%' THEN 'Mercedes-Benz'
            WHEN productName LIKE '%Aston%' THEN 'Aston Martin'
            WHEN productName LIKE '%Porsche%' THEN 'Porsche'
            WHEN productName LIKE '%Honda%' THEN 'Honda'
            WHEN productName LIKE '%Chrysler%' THEN 'Chrysler'
            WHEN productName LIKE '%Toyota%' THEN 'Toyota'
            WHEN productName LIKE '%Suzuki%' THEN 'Suzuki'
            WHEN productName LIKE '%Maxwell%' THEN 'Maxwell'
            WHEN productName LIKE '%Vespa%' THEN 'Vespa'
            WHEN productName LIKE '%Triumph%' THEN 'Triumph'
            WHEN productName LIKE '%Buick%' THEN 'Buick'
            WHEN productName LIKE '%Corvette%' THEN 'Chevrolet'
            WHEN productName LIKE '%Cadillac%' THEN 'Cadillac'
            WHEN productName LIKE '%BMW%' THEN 'BMW'
            WHEN productName LIKE '%Shelby%' THEN 'Ford'
            WHEN productName LIKE '%Volkswagen%' OR productName LIKE '%VW%'THEN 'Volkswagen'
            WHEN productName LIKE '%Ducati%' THEN 'Ducati'
            WHEN productName LIKE '%Jaguar%' THEN 'Jaguar'
            WHEN productName LIKE '%Citroen%' THEN 'Citroen'
            WHEN productName LIKE '%GM%' THEN 'General Motors'
            WHEN productName LIKE '%Camero%' THEN 'Chevy'
            WHEN productName LIKE '%Lamborghini%' THEN 'Lamborghini'
            WHEN productName LIKE '%Greyhound%' THEN 'General Motors'
            WHEN productName LIKE '%Yamaha%' THEN 'Yamaha'
            WHEN productName LIKE '%Camaro%' THEN 'Chevrolet'
            ELSE NULL
        END as make,
        CASE
            WHEN productName LIKE '%Harley%' THEN 'United States'
            WHEN productName LIKE '%Renault%' THEN 'France'
            WHEN productName LIKE '%Guzzi%' THEN 'Italy'
            WHEN productName LIKE '%Alfa%' THEN 'Italy'
            WHEN productName LIKE '%Lancia%' THEN 'Italy'
            WHEN productName LIKE '%Ford%' THEN 'United States'
            WHEN productName LIKE '%Ferrari%' THEN 'Italy'
            WHEN productName LIKE '%Setra%' THEN 'Germany'
            WHEN productName LIKE '%Corvair%' THEN 'United States'
            WHEN productName LIKE '%Dodge%' THEN 'United States'
            WHEN productName LIKE '%Plymouth%' THEN 'United States'
            WHEN productName LIKE '%Chev%' THEN 'United States'
            WHEN productName LIKE '%Mazda%' THEN 'Japan'
            WHEN productName LIKE '%Lincoln%' THEN 'United States'
            WHEN productName LIKE '%Benz%' OR productName LIKE '%Mercedes%' THEN 'Germany'
            WHEN productName LIKE '%Aston%' THEN 'United Kingdom'
            WHEN productName LIKE '%Porsche%' THEN 'Germany'
            WHEN productName LIKE '%Honda%' THEN 'Japan'
            WHEN productName LIKE '%Chrysler%' THEN 'United States'
            WHEN productName LIKE '%Toyota%' THEN 'Japan'
            WHEN productName LIKE '%Suzuki%' THEN 'Japan'
            WHEN productName LIKE '%Maxwell%' THEN 'United States'
            WHEN productName LIKE '%Vespa%' THEN 'Italy'
            WHEN productName LIKE '%Triumph%' THEN 'United Kingdom'
            WHEN productName LIKE '%Buick%' THEN 'United States'
            WHEN productName LIKE '%Corvette%' THEN 'United States'
            WHEN productName LIKE '%Cadillac%' THEN 'United States'
            WHEN productName LIKE '%BMW%' THEN 'Germany'
            WHEN productName LIKE '%Shelby%' THEN 'United States'
            WHEN productName LIKE '%Volkswagen%' OR productName LIKE '%VW%'THEN 'Germany'
            WHEN productName LIKE '%Ducati%' THEN 'Italy'
            WHEN productName LIKE '%Jaguar%' THEN 'United Kingdom'
            WHEN productName LIKE '%Citroen%' THEN 'France'
            WHEN productName LIKE '%GM%' THEN 'United States'
            WHEN productName LIKE '%Camero%' THEN 'United States'
            WHEN productName LIKE '%Lamborghini%' THEN 'Italy'
            WHEN productName LIKE '%BSA' THEN 'United Kingdom'
            WHEN productName LIKE '%Horch%' THEN 'Germany'
            WHEN productName LIKE '%Greyhound%' THEN 'United States'
            WHEN productName LIKE '%Peterbilt%' THEN 'United States'
            WHEN productName LIKE '%Yamaha%' THEN 'Japan'
            WHEN productName LIKE '%Camaro%' THEN 'United States'
            ELSE NULL
        END as origin,
       productname
  FROM products
 GROUP BY make
 ORDER BY origin
 